#!/bin/sh

# Script to setup the testing environment

audit_control="/etc/security/audit_control"
audit_daemon='/etc/rc.conf'

# Inserts auditd_enable="YES" in /etc/rc.conf
# if not already done
enable_audit()
{
    sed -i "" '/auditd_enable/d' "$audit_daemon"
    echo "auditd_enable=\"YES\"" >> "$audit_daemon"
    echo "Audit daemon configured .. ✔"
    return
}

# Set flags as (all) audit_class
set_flag()
{
    sed -i "" '/\<flags:/s/\(.*\)/flags:all/' "$audit_control"
    echo "Set Attributed flag: (all) .. ✔"
    return
}

set_flag
enable_audit
